import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import devjosh from "../public/joshuarosa.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/robofriends.png";
import web2 from "../public/dealsella1.png";
import web5 from "../public/snaker.png";
import web4 from "../public/web4.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Joshua Almodovar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-center">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="curser-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://docs.google.com/document/d/1l_GCNYcvThqNFziIVk0KUtepxCR_69g-/edit?usp=sharing&ouid=109829942098253021161&rtpof=true&sd=true"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Joshua Almodovar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Front end Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              I am growing my programming skills and learning new things daily!
              Welcome to my portfolio! Please reach out via linkedin or
              from the email on my resume if you would like to collaborate!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://github.com/jalmo1" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/jalmo1/" target="_blank">
              <AiFillLinkedin />
            </a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={devjosh} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section className="min-h-screen py-10">
          <div className="text-center py-10">
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              What I offer
            </h3>
            <p className="text-md leading-8 text-gray-800 md:text-lg dark:text-gray-200">
              In the beginning of my developer journey, I was learning Python to
              build back end servers and now I mainly use Javascript and React
              to create beautiful web applications.
              <br />I have experience with working with big
              <span className="text-teal-500"> corporations</span> and also
              collaborating on
              <span className="text-teal-500"> open source</span> projects.
            </p>
          </div>
          <div className="md:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-full dark:bg-white">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto pt-5"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p>
                I always strive to make my projects look modern with an strong
                emphasis on designing UX/UI forward applications.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use:</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-full dark:bg-white">
              <Image
                src={code}
                width={100}
                height={100}
                className="mx-auto pt-5"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Development</h3>
              <p>
                I love writing clean and easy to read code. I practice daily so
                I can get better in my writing development skill.
              </p>
              <h4 className="py-4 text-teal-600">Development tools I use:</h4>
              <p className="text-gray-800 py-1">Grammerly</p>
              <p className="text-gray-800 py-1">VSCode</p>
              <p className="text-gray-800 py-1">Stack Overflow</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 w-full dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto pt-5"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Consultations and Collaborations
              </h3>
              <p>
                I love to get my hands dirty on cool projects and consult on
                projects that so I can make someones website / app 100% better.
              </p>
              <h4 className="py-4 text-teal-600">Collaboration tools I use:</h4>
              <p className="text-gray-800 py-1">Github</p>
              <p className="text-gray-800 py-1">Stack Overflow (...Again)</p>
              <p className="text-gray-800 py-1">Discord</p>
            </div>
          </div>
        </section>
        {/* <section>
          <div>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Portfolio
            </h3>
            <p className="text-md leading-8 text-gray-800 md:text-lg dark:text-gray-200">
              Below are a few of the projects I have built or collaborated on. I
              have some projects from when I was attending a full stack bootcamp
              and some personal projects as well. If you would like to see more,
              feel free to click the GitHub icon at the top of the screen.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section> */}
      </main>
    </div>
  );
}
